In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [ ]:
import pandas as pd
df=pd.read_csv('/content/CAR DETAILS FROM CAR DEKHO.csv')
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [ ]:
df.tail()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [ ]:
df.columns.unique()

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [ ]:
df.describe()

              year  selling_price      km_driven
count  4340.000000   4.340000e+03    4340.000000
mean   2013.090783   5.041273e+05   66215.777419
std       4.215344   5.785487e+05   46644.102194
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.087498e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [ ]:
df.describe(include=object)

                          name    fuel seller_type transmission        owner
count                     4340    4340        4340         4340         4340
unique                    1491       5           3            2            5
top     Maruti Swift Dzire VDI  Diesel  Individual       Manual  First Owner
freq                        69    2153        3244         3892         2832

In [ ]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [ ]:
df['name'].unique()
df['name'].nunique()

1491

In [ ]:
df['brand'] = df['name'].str.split(' ').str[0]
df['brand'].nunique()

29

In [ ]:
df.drop(['name'],axis=1,inplace=True)
df

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,brand
0,2007,60000,70000,Petrol,Individual,Manual,First Owner,Maruti
1,2007,135000,50000,Petrol,Individual,Manual,First Owner,Maruti
2,2012,600000,100000,Diesel,Individual,Manual,First Owner,Hyundai
3,2017,250000,46000,Petrol,Individual,Manual,First Owner,Datsun
4,2014,450000,141000,Diesel,Individual,Manual,Second Owner,Honda
...,...,...,...,...,...,...,...,...
4335,2014,409999,80000,Diesel,Individual,Manual,Second Owner,Hyundai
4336,2014,409999,80000,Diesel,Individual,Manual,Second Owner,Hyundai
4337,2009,110000,83000,Petrol,Individual,Manual,Second Owner,Maruti
4338,2016,865000,90000,Diesel,Individual,Manual,First Owner,Hyundai
4339,2016,225000,40000,Petrol,Individual,Manual,First Owner,Renault

In [ ]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Fourth & Above Owner',
       'Third Owner', 'Test Drive Car'], dtype=object)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
order = [['Test Drive Car', 'First Owner', 'Second Owner', 'Third Owner', 'Fourth & Above Owner']]
ordinal_enc = OrdinalEncoder(categories=order,dtype=int)
df['owner_encoded'] = ordinal_enc.fit_transform(df[['owner']])
df = df.drop('owner', axis=1)
df

,year,selling_price,km_driven,fuel,seller_type,transmission,brand,owner_encoded
0,2007,60000,70000,Petrol,Individual,Manual,Maruti,1
1,2007,135000,50000,Petrol,Individual,Manual,Maruti,1
2,2012,600000,100000,Diesel,Individual,Manual,Hyundai,1
3,2017,250000,46000,Petrol,Individual,Manual,Datsun,1
4,2014,450000,141000,Diesel,Individual,Manual,Honda,2
...,...,...,...,...,...,...,...,...
4335,2014,409999,80000,Diesel,Individual,Manual,Hyundai,2
4336,2014,409999,80000,Diesel,Individual,Manual,Hyundai,2
4337,2009,110000,83000,Petrol,Individual,Manual,Maruti,2
4338,2016,865000,90000,Diesel,Individual,Manual,Hyundai,1
4339,2016,225000,40000,Petrol,Individual,Manual,Renault,1

In [ ]:
from sklearn.preprocessing import OneHotEncoder

one_hot_fuel = OneHotEncoder(sparse_output=False, dtype=int)
encoded_fuel = one_hot_fuel.fit_transform(df[['fuel']])
colname_fuel = one_hot_fuel.get_feature_names_out()
df1 = pd.DataFrame(encoded_fuel, columns=colname_fuel)
df = pd.concat([df, df1], axis=1)
df = df.drop('fuel', axis=1)
df

,year,selling_price,km_driven,seller_type,transmission,brand,owner_encoded,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol
0,2007,60000,70000,Individual,Manual,Maruti,1,0,0,0,0,1
1,2007,135000,50000,Individual,Manual,Maruti,1,0,0,0,0,1
2,2012,600000,100000,Individual,Manual,Hyundai,1,0,1,0,0,0
3,2017,250000,46000,Individual,Manual,Datsun,1,0,0,0,0,1
4,2014,450000,141000,Individual,Manual,Honda,2,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
4335,2014,409999,80000,Individual,Manual,Hyundai,2,0,1,0,0,0
4336,2014,409999,80000,Individual,Manual,Hyundai,2,0,1,0,0,0
4337,2009,110000,83000,Individual,Manual,Maruti,2,0,0,0,0,1
4338,2016,865000,90000,Individual,Manual,Hyundai,1,0,1,0,0,0
4339,2016,225000,40000,Individual,Manual,Renault,1,0,0,0,0,1

In [ ]:
one_hot_seller = OneHotEncoder(sparse_output=False, dtype=int)
encoded_seller = one_hot_seller.fit_transform(df[['seller_type']])
colname_seller = one_hot_seller.get_feature_names_out()
df2 = pd.DataFrame(encoded_seller, columns=colname_seller)
df = pd.concat([df, df2], axis=1)
df = df.drop('seller_type', axis=1)
df

,year,selling_price,km_driven,transmission,brand,owner_encoded,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer
0,2007,60000,70000,Manual,Maruti,1,0,0,0,0,1,0,1,0
1,2007,135000,50000,Manual,Maruti,1,0,0,0,0,1,0,1,0
2,2012,600000,100000,Manual,Hyundai,1,0,1,0,0,0,0,1,0
3,2017,250000,46000,Manual,Datsun,1,0,0,0,0,1,0,1,0
4,2014,450000,141000,Manual,Honda,2,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,2014,409999,80000,Manual,Hyundai,2,0,1,0,0,0,0,1,0
4336,2014,409999,80000,Manual,Hyundai,2,0,1,0,0,0,0,1,0
4337,2009,110000,83000,Manual,Maruti,2,0,0,0,0,1,0,1,0
4338,2016,865000,90000,Manual,Hyundai,1,0,1,0,0,0,0,1,0
4339,2016,225000,40000,Manual,Renault,1,0,0,0,0,1,0,1,0

In [ ]:
one_hot_trans = OneHotEncoder(sparse_output=False, dtype=int)
encoded_trans = one_hot_trans.fit_transform(df[['transmission']])
colname_trans = one_hot_trans.get_feature_names_out()
df3 = pd.DataFrame(encoded_trans, columns=colname_trans)
df = pd.concat([df, df3], axis=1)
df = df.drop('transmission', axis=1)
df

,year,selling_price,km_driven,brand,owner_encoded,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Dealer,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Automatic,transmission_Manual
0,2007,60000,70000,Maruti,1,0,0,0,0,1,0,1,0,0,1
1,2007,135000,50000,Maruti,1,0,0,0,0,1,0,1,0,0,1
2,2012,600000,100000,Hyundai,1,0,1,0,0,0,0,1,0,0,1
3,2017,250000,46000,Datsun,1,0,0,0,0,1,0,1,0,0,1
4,2014,450000,141000,Honda,2,0,1,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,2014,409999,80000,Hyundai,2,0,1,0,0,0,0,1,0,0,1
4336,2014,409999,80000,Hyundai,2,0,1,0,0,0,0,1,0,0,1
4337,2009,110000,83000,Maruti,2,0,0,0,0,1,0,1,0,0,1
4338,2016,865000,90000,Hyundai,1,0,1,0,0,0,0,1,0,0,1
4339,2016,225000,40000,Renault,1,0,0,0,0,1,0,1,0,0,1

In [ ]:
one_hot_brand = OneHotEncoder(sparse_output=False, dtype=int)
encoded_brand = one_hot_brand.fit_transform(df[['brand']])
colname_brand = one_hot_brand.get_feature_names_out()
df4 = pd.DataFrame(encoded_brand, columns=colname_brand)
df = pd.concat([df, df4], axis=1)
df = df.drop('brand', axis=1)
df

,year,selling_price,km_driven,owner_encoded,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Dealer,...,brand_Mercedes-Benz,brand_Mitsubishi,brand_Nissan,brand_OpelCorsa,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo
0,2007,60000,70000,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2007,135000,50000,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,2012,600000,100000,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2017,250000,46000,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,2014,450000,141000,2,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,2014,409999,80000,2,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4336,2014,409999,80000,2,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4337,2009,110000,83000,2,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4338,2016,865000,90000,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4339,2016,225000,40000,1,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0

In [ ]:
df.shape
df

,year,selling_price,km_driven,owner_encoded,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Dealer,...,brand_Mercedes-Benz,brand_Mitsubishi,brand_Nissan,brand_OpelCorsa,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo
0,2007,60000,70000,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2007,135000,50000,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,2012,600000,100000,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2017,250000,46000,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,2014,450000,141000,2,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,2014,409999,80000,2,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4336,2014,409999,80000,2,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4337,2009,110000,83000,2,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4338,2016,865000,90000,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4339,2016,225000,40000,1,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0

In [ ]:
x = df.drop('selling_price', axis=1)
y = df['selling_price']
x
y

0        60000
1       135000
2       600000
3       250000
4       450000
         ...
4335    409999
4336    409999
4337    110000
4338    865000
4339    225000
Name: selling_price, Length: 4340, dtype: int64

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=42)
print('total_data:',df.shape[0],'rows')
print('xtrain:',xtrain.shape[0],'rows')
print('xtest:',xtest.shape[0],'rows')
print('ytrain:',ytrain.shape[0],'rows')
print('ytest:',ytest.shape[0],'rows')

total_data: 4340 rows
xtrain: 3038 rows
xtest: 1302 rows
ytrain: 3038 rows
ytest: 1302 rows

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.transform(xtest)

In [ ]:
model=LinearRegression()
model.fit(xtrain,ytrain)

LinearRegression()

In [ ]:
#training and testing data efficiency :
print('training efficiency:',model.score(xtrain,ytrain))
print('testing efficiency:',model.score(xtest,ytest))

training efficiency: 0.7195764286260922
testing efficiency: 0.5768681052725875

In [ ]:
ypred=model.predict(xtest)
ypred

array([258693.4979787 , 477342.78041197, 127710.20005675, ...,
       258292.55711737, 603984.07079805, 190311.63747329])

In [ ]:
#model evoluation:
print("r2_score:",r2_score(ytest,ypred))
print("MSE:",mean_squared_error(ytest,ypred))
print("MAE:",mean_absolute_error(ytest,ypred))

r2_score: 0.5768681052725875
MSE: 125103538832.44379
MAE: 183094.06223184563

In [ ]:
# new car prediction (full pipeline):

new_car = pd.DataFrame(0, index=[0], columns=x.columns)

new_car['year'] = 2015
new_car['km_driven'] = 40000
new_car['owner_encoded'] = 1
new_car['fuel_Petrol'] = 1
new_car['seller_type_Individual'] = 1
new_car['transmission_Manual'] = 1
new_car['brand_Maruti'] = 1

new_car = new_car[x.columns]  # ensure column order matches training exactly

new_car_scaled = scaler.transform(new_car)
predicted_price = model.predict(new_car_scaled)

print("Predicted price:", predicted_price[0])
new_car

Predicted price: -75105953.27154288

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

,year,km_driven,owner_encoded,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Dealer,seller_type_Individual,...,brand_Mercedes-Benz,brand_Mitsubishi,brand_Nissan,brand_OpelCorsa,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo
0,2015,40000,1,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0